import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000';
const avatar = { base: 'owl', color: 'yellow', accessory: 'glasses' };
const apiFetch = (path: string, init: RequestInit = {}) => fetch(`${API}${path}`, { ...init, credentials: 'include' });

function App() {
  const [user, setUser] = useState<any>(null); const [topics, setTopics] = useState<any[]>([]); const [job, setJob] = useState<any>(null); const [pkg, setPkg] = useState<any>(null); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { Promise.all([apiFetch('/api/me'), apiFetch('/api/curriculum/gate-cs')]).then(async ([me, curriculum]) => { if (me.status === 401) { window.location.assign(`${API}/auth/google`); return; } if (!me.ok || !curriculum.ok) throw new Error('EduSwarm is unavailable. Please try again.'); setUser(await me.json()); setTopics((await curriculum.json()).topics); }).catch((reason: Error) => setError(reason.message)); }, []);
  async function onboard(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const r = await apiFetch('/api/onboarding', { method:'POST', headers:{'content-type':'application/json'}, body: JSON.stringify({ name, goal:'gate-cs', avatar }) }); if (!r.ok) throw new Error('We could not set up your learning plan.'); setUser(await r.json()); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Request failed.'); } finally { setBusy(false); } }
  async function start(topicId: string) { setError(''); try { const r = await apiFetch('/api/jobs', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ topicId }) }); if (!r.ok) throw new Error('We could not start this topic.'); const initial = await r.json(); setJob(initial); const events = new EventSource(`${API}/api/jobs/${initial.id}/events`, { withCredentials: true }); events.onmessage = async e => { const next = JSON.parse(e.data); setJob(next); if (next.status === 'completed') { events.close(); const content = await apiFetch(`/api/content/${next.id}`); if (content.ok) setPkg(await content.json()); else setError('The verified package could not be loaded.'); } if (next.status === 'failed') events.close(); }; events.onerror = () => { events.close(); setError('Connection to the learning team was interrupted. Retry the topic to continue.'); }; } catch (reason) { setError(reason instanceof Error ? reason.message : 'Request failed.'); } }
  if (!user?.goals?.length) return <main className="center"><section className="onboard card"><div className="logo">✦ EduSwarm</div><h1>Build your learning team.</h1><p>Tell the Dean your goal. Specialist agents will research, verify, and help you study every day.</p>{error && <p className="error" role="alert">{error}</p>}<form onSubmit={onboard}><label>Your name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ada Lovelace" required /></label><label>Choose your first goal<select defaultValue="gate-cs"><option value="gate-cs">Clear GATE CS</option><option>Master Web Development</option><option>Learn AI/ML</option></select></label><button disabled={busy}>{busy ? 'Setting up…' : 'Start my journey →'}</button></form></section></main>;
  return <main><header><div className="logo">✦ EduSwarm</div><div className="user-chip"><span className="avatar">🦉</span> {user.name}</div></header><div className="layout"><aside><p className="eyebrow">MY GOAL</p><div className="goal-card yellow"><b>GATE CS</b><span>Algorithms · {user.goals[0].progress}% complete</span></div><nav><a className="active">◈ Study plan</a><a>▣ Flashcards</a><a>✎ Practice</a><a>♢ Progress</a></nav><div className="streak">🔥 <b>3 day streak</b><small>Keep the rhythm going!</small></div></aside><section className="content"><div className="hero"><div><p className="eyebrow">THE DEAN'S BRIEFING</p><h1>Good morning, {user.name}.</h1><p>Your team picked the next best topic based on prerequisites and your 60-minute daily plan.</p></div><div className="dean">🧠<span>Dean</span></div></div>{job ? <JobCard job={job} pkg={pkg} /> : <><div className="section-head"><h2>Algorithms roadmap</h2><span className="badge">3 TOPICS</span></div><div className="topics">{topics.map((topic, i) => <article className={`topic card ${topic.status}`} key={topic.id}><div className="topic-icon">{i === 0 ? '∿' : i === 1 ? '▦' : '◌'}</div><div><h3>{topic.title}</h3><p>{topic.description}</p><small>{topic.status === 'locked' ? '🔒 Complete the previous topic first' : 'Ready to learn · 25 min'}</small></div><button disabled={topic.status === 'locked'} onClick={() => start(topic.id)}>{topic.status === 'locked' ? 'Locked' : 'Study topic →'}</button></article>)}</div><div className="daily card"><div><p className="eyebrow">PROBLEM OF THE DAY</p><h2>Can you spot the complexity?</h2><p>Warm up with a 5-minute concept challenge.</p></div><span className="new-badge">NEW</span></div></>}</section></div></main>;
}
function JobCard({ job, pkg }: any) { return <section className="job card"><div className="job-head"><div><p className="eyebrow">YOUR LEARNING TEAM</p><h2>{job.status === 'completed' ? 'Your verified package is ready.' : 'The team is working on it…'}</h2><p>{job.message}</p></div><div className="spinner">{job.status === 'completed' ? '✓' : '✦'}</div></div>{job.status !== 'completed' && <div className="progress-track"><div style={{ width: `${Math.min(92, Math.max(8, job.stage === 'Fact-Checker' ? 80 : 40))}%` }} /></div>}{pkg && <div className="package"><div className="verified">✓ FACT-CHECKED · {pkg.verification.claimsChecked} CLAIMS · {pkg.verification.sources.length} SOURCES</div><h2>{pkg.title}</h2>{pkg.notes.sections.map((s:any)=><div className="note" key={s.heading}><h3>{s.heading}</h3><p>{s.body}</p></div>)}<div className="columns"><div><h3>Flashcards ({pkg.flashcards.length})</h3>{pkg.flashcards.map((f:any)=><div className="mini-card" key={f.question}><b>{f.question}</b><span>{f.answer}</span></div>)}</div><div><h3>Practice quiz</h3><div className="quiz"><b>{pkg.quiz[0].question}</b>{pkg.quiz[0].options.map((o:string)=><label key={o}><input type="radio" name="q" /> {o}</label>)}</div></div></div></div>}</section>; }
createRoot(document.getElementById('root')!).render(<App />);
